//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/InputActionsConsole.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActionsConsole: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActionsConsole()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionsConsole"",
    ""maps"": [
        {
            ""name"": ""ConsoleToggle"",
            ""id"": ""c14c4b59-7bec-4c49-898c-e3ff5c3a287e"",
            ""actions"": [
                {
                    ""name"": ""ToggleDebug"",
                    ""type"": ""Button"",
                    ""id"": ""b6cf0925-a0df-4696-a38c-1e90c1841366"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Return"",
                    ""type"": ""Button"",
                    ""id"": ""37b70b84-db27-4e82-bc23-f6d2e9234bdb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""93bc510f-feb0-4b36-9639-3076fcc83574"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDebug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57a55edb-1636-4999-954e-30d3941bfda3"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ConsoleToggle
        m_ConsoleToggle = asset.FindActionMap("ConsoleToggle", throwIfNotFound: true);
        m_ConsoleToggle_ToggleDebug = m_ConsoleToggle.FindAction("ToggleDebug", throwIfNotFound: true);
        m_ConsoleToggle_Return = m_ConsoleToggle.FindAction("Return", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ConsoleToggle
    private readonly InputActionMap m_ConsoleToggle;
    private List<IConsoleToggleActions> m_ConsoleToggleActionsCallbackInterfaces = new List<IConsoleToggleActions>();
    private readonly InputAction m_ConsoleToggle_ToggleDebug;
    private readonly InputAction m_ConsoleToggle_Return;
    public struct ConsoleToggleActions
    {
        private @InputActionsConsole m_Wrapper;
        public ConsoleToggleActions(@InputActionsConsole wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleDebug => m_Wrapper.m_ConsoleToggle_ToggleDebug;
        public InputAction @Return => m_Wrapper.m_ConsoleToggle_Return;
        public InputActionMap Get() { return m_Wrapper.m_ConsoleToggle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ConsoleToggleActions set) { return set.Get(); }
        public void AddCallbacks(IConsoleToggleActions instance)
        {
            if (instance == null || m_Wrapper.m_ConsoleToggleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ConsoleToggleActionsCallbackInterfaces.Add(instance);
            @ToggleDebug.started += instance.OnToggleDebug;
            @ToggleDebug.performed += instance.OnToggleDebug;
            @ToggleDebug.canceled += instance.OnToggleDebug;
            @Return.started += instance.OnReturn;
            @Return.performed += instance.OnReturn;
            @Return.canceled += instance.OnReturn;
        }

        private void UnregisterCallbacks(IConsoleToggleActions instance)
        {
            @ToggleDebug.started -= instance.OnToggleDebug;
            @ToggleDebug.performed -= instance.OnToggleDebug;
            @ToggleDebug.canceled -= instance.OnToggleDebug;
            @Return.started -= instance.OnReturn;
            @Return.performed -= instance.OnReturn;
            @Return.canceled -= instance.OnReturn;
        }

        public void RemoveCallbacks(IConsoleToggleActions instance)
        {
            if (m_Wrapper.m_ConsoleToggleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IConsoleToggleActions instance)
        {
            foreach (var item in m_Wrapper.m_ConsoleToggleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ConsoleToggleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ConsoleToggleActions @ConsoleToggle => new ConsoleToggleActions(this);
    public interface IConsoleToggleActions
    {
        void OnToggleDebug(InputAction.CallbackContext context);
        void OnReturn(InputAction.CallbackContext context);
    }
}
